// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Clip-it",
    platforms: [
        .iOS("17.0")
    ],
    products: [
        .iOSApplication(
            name: "Clip-it",
            targets: ["AppModule"],
            bundleIdentifier: "Diegogtz.ClipIt",
            teamIdentifier: "6CXRQS8B7G",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.brown),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .camera(purposeString: "Clip-it uses your camera to allow you to capture your moments and clip them whenever you want."),
                .microphone(purposeString: "Clip-it uses your mic to allow you to record your moment and clip them whenever you want.")
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(url: "https://github.com/dmrschmidt/DSWaveformImage", "14.2.2"..<"15.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DSWaveformImage", package: "dswaveformimage"),
                .product(name: "DSWaveformImageViews", package: "dswaveformimage")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)